version: "2"
services:
  world:
    image: dstacademy/dontstarvetogether
    container_name: world
    hostname: world
    tty: true
    stdin_open: true
    command: dst-server start --update=all
    env_file: world.env
    ports:
      - "10999:10999/udp"
    volumes:
      - ./world:/var/lib/dsta/cluster
